name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  job1:
    runs-on: ubuntu-latest
    outputs:
      shared_value: ${{ steps.set_env.outputs.shared_value }}
      test: ${{ steps.set_env_new.outputs.test }}
    steps:
      - name: Set ENV（旧写法，不推荐，该写法可能在将来会被删除）
        id: set_env
        run: echo "::set-output name=shared_value::shared_value"

      - name: Set ENV（新写法，推荐）
        id: set_env_new
        run: echo "test=123456" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Get ENV from job1 shared_value
        run: echo "The value of shared_value is ${{needs.job1.outputs.shared_value}}"
      - name: Get ENV from job1 test
        run: echo "The value of test is ${{needs.job1.outputs.test}}"

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      generic_package_name: my_package
    # 仅在推送代码时执行
    if: github.event_name == 'push'
    steps:

      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        # bash, sh, cmd, powershell, pwsh
        # shell 类型必须为 sh，否则：
        # $GITHUB_ENV：仅支持 ubuntu、macos
        # $env:GITHUB_ENV：仅支持 windows
        shell: sh
        run: |
          echo "YEAR_MONTH_DAY=$(date +'%Y-%m-%dZ')" >> $GITHUB_ENV
          echo "YEAR_MONTH_DAY_HOUR=$(date +'%Y-%m-%dT%HZ')" >> $GITHUB_ENV
          echo "YEAR_MONTH_DAY_HOUR_MINUTE=$(date +'%Y-%m-%dT%H-%MZ')" >> $GITHUB_ENV
          echo "BODY=自动推送时的发布" >> $GITHUB_ENV

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            gitmoji.md
          body: ${{ env.BODY }}
          # draft: 草稿状态，为 true 时，不创建标签，默认为 false
          # draft: true
          # prerelease：是否发布预发布版，默认为 false
          prerelease: true
          name: v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}
          tag: v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # 获取所有的代码历史记录，包括分支和标签
          fetch-depth: 0

      # 将代码同步到 极狐GitLab
      - name: Sync JihuLab
        run: |
          git config --global user.email "xuxiaowei@xuxiaowei.com.cn"
          git config --global user.name "徐晓伟"
          # 设置 SSH 秘钥
          mkdir -p ~/.ssh
          echo "${{ secrets.JIHULAB_ID_RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s) && ssh-add ~/.ssh/id_rsa
          # 信任域名
          ssh-keyscan -H jihulab.com >> ~/.ssh/known_hosts
          # 查看当前分支
          echo 当前分支：$GITHUB_REF_NAME
          # 查看远端 极狐GitLab
          echo git@jihulab.com:$GITHUB_REPOSITORY.git
          # 添加远端 极狐GitLab
          git remote add jihulab git@jihulab.com:$GITHUB_REPOSITORY.git
          # 拉取
          git pull --progress -v --no-rebase jihulab $GITHUB_REF_NAME
          # 推送当前分支
          git push --progress jihulab $GITHUB_REF_NAME:$GITHUB_REF_NAME
          # 推送所有标签
          git push --tags --progress jihulab

      - name: Publish JihuLab
        run: |
          echo "GITHUB_REPOSITORY:$GITHUB_REPOSITORY"
          jihulab_project_id=$(printf "%s" "$GITHUB_REPOSITORY" | jq -s -R -r @uri)
          echo "jihulab_project_id:$jihulab_project_id"
          
          # 发布 极狐GitLab：https://docs.gitlab.cn/jh/api/releases/#%E5%88%9B%E5%BB%BA%E5%8F%91%E5%B8%83
          curl --header 'Content-Type: application/json' \
            --header "PRIVATE-TOKEN: ${{ secrets.JIHULAB_PRIVATE_TOKEN }}" \
            --data '{ "name": "v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}", "tag_name": "v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}", "description": "" }' \
            --request POST "https://jihulab.com/api/v4/projects/$jihulab_project_id/releases" && echo "\n发布 极狐GitLab 完成"
          
          # 发布 包文件：https://docs.gitlab.cn/jh/user/packages/generic_packages/index.html#%E5%8F%91%E5%B8%83%E5%8C%85%E6%96%87%E4%BB%B6
          curl \
            --header "PRIVATE-TOKEN: ${{ secrets.JIHULAB_PRIVATE_TOKEN }}" \
            --upload-file gitmoji.md \
            "https://jihulab.com/api/v4/projects/$jihulab_project_id/packages/generic/$generic_package_name/v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}/gitmoji.md?select=package_file" > jihulab_response.json && echo "\n发布 包文件 完成"
          
          package_file_id=$(jq -r '.id' jihulab_response.json)
          echo $package_file_id
          # 创建 发布链接：https://docs.gitlab.cn/jh/api/releases/links.html#%E5%88%9B%E5%BB%BA%E5%8F%91%E5%B8%83%E9%93%BE%E6%8E%A5
          curl --request POST \
            --header "PRIVATE-TOKEN: ${{ secrets.JIHULAB_PRIVATE_TOKEN }}" \
            --data name="gitmoji.md" \
            --data url="https://jihulab.com/$GITHUB_REPOSITORY/-/package_files/$package_file_id/download" \
            "https://jihulab.com/api/v4/projects/$jihulab_project_id/releases/v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}/assets/links" && echo "\n创建 发布链接 完成"


      # 将代码同步到 GitLab
      - name: Sync GitLab
        run: |
          git config --global user.email "xuxiaowei@xuxiaowei.com.cn"
          git config --global user.name "徐晓伟"
          # 设置 SSH 秘钥
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_ID_RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s) && ssh-add ~/.ssh/id_rsa
          # 信任域名
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
          # 查看当前分支
          echo 当前分支：$GITHUB_REF_NAME
          # 查看远端 极狐GitLab
          echo git@gitlab.com:$GITHUB_REPOSITORY.git
          # 添加远端 极狐GitLab
          git remote add gitlab git@gitlab.com:$GITHUB_REPOSITORY.git
          # 拉取
          git pull --progress -v --no-rebase gitlab $GITHUB_REF_NAME
          # 推送当前分支
          git push --progress gitlab $GITHUB_REF_NAME:$GITHUB_REF_NAME
          # 推送所有标签
          git push --tags --progress gitlab

      - name: Publish GitLab
        run: |
          echo "GITHUB_REPOSITORY:$GITHUB_REPOSITORY"
          gitlab_project_id=$(printf "%s" "$GITHUB_REPOSITORY" | jq -s -R -r @uri)
          echo "gitlab_project_id:$gitlab_project_id"
          
          # 发布 极狐GitLab：https://docs.gitlab.cn/jh/api/releases/#%E5%88%9B%E5%BB%BA%E5%8F%91%E5%B8%83
          curl --header 'Content-Type: application/json' \
            --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_PRIVATE_TOKEN }}" \
            --data '{ "name": "v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}", "tag_name": "v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}", "description": "" }' \
            --request POST "https://gitlab.com/api/v4/projects/$gitlab_project_id/releases"
          
          # 创建发布链接：https://docs.gitlab.cn/jh/api/releases/links.html#%E5%88%9B%E5%BB%BA%E5%8F%91%E5%B8%83%E9%93%BE%E6%8E%A5
          curl --request POST \
            --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_PRIVATE_TOKEN }}" \
            --data name="gitmoji.md" \
            --data url="https://github.com/$GITHUB_REPOSITORY/releases/download/v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}/gitmoji.md" \
            "https://gitlab.com/api/v4/projects/$gitlab_project_id/releases/v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}/assets/links"

      # 将代码同步到 码云Gitee
      - name: Sync Gitee
        run: |
          git config --global user.email "xuxiaowei@xuxiaowei.com.cn"
          git config --global user.name "徐晓伟"
          git remote add gitee https://xuxiaowei-com-cn:${{ secrets.GITEE_PRIVATE_TOKEN }}@gitee.com/$GITHUB_REPOSITORY.git
          # 推送当前分支
          git push --progress gitee $GITHUB_REF_NAME:$GITHUB_REF_NAME
          # 推送所有标签
          git push --tags --progress gitee

      - name: Publish Gitee
        run: |
          # https://gitee.com/api/v5/swagger#/postV5ReposOwnerRepoReleases
          curl -X POST \
            --header 'Content-Type: application/json;charset=UTF-8' \
            "https://gitee.com/api/v5/repos/$GITHUB_REPOSITORY/releases" \
            -d '{"access_token":"${{ secrets.GITEE_PRIVATE_TOKEN }}","tag_name":"v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}","name":"v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}","body":"${{ env.BODY }}","prerelease":"true","target_commitish":"$GITHUB_REF_NAME"}'
