name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # 仅在推送代码时执行
    if: github.event_name == 'push'
    steps:

      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        # bash, sh, cmd, powershell, pwsh
        # shell 类型必须为 sh，否则：
        # $GITHUB_ENV：仅支持 ubuntu、macos
        # $env:GITHUB_ENV：仅支持 windows
        shell: sh
        run: |
          echo "YEAR_MONTH_DAY=$(date +'%Y-%m-%dZ')" >> $GITHUB_ENV
          echo "YEAR_MONTH_DAY_HOUR=$(date +'%Y-%m-%dT%HZ')" >> $GITHUB_ENV
          echo "YEAR_MONTH_DAY_HOUR_MINUTE=$(date +'%Y-%m-%dT%H-%MZ')" >> $GITHUB_ENV
          echo "BODY=自动推送时的发布"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            gitmoji.md
          body: ${{ env.BODY }}
          # draft: 草稿状态，为 true 时，不创建标签，默认为 false
          # draft: true
          # prerelease：是否发布预发布版，默认为 false
          prerelease: true
          name: v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}
          tag: v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # 获取所有的代码历史记录，包括分支和标签
          fetch-depth: 0

      # 将代码同步到 极狐GitLab
      - name: Sync JihuLab
        run: |
          git config --global user.email "xuxiaowei@xuxiaowei.com.cn"
          git config --global user.name "徐晓伟"
          # 设置 SSH 秘钥
          mkdir -p ~/.ssh
          echo "${{ secrets.JIHULAB_ID_RSA }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s) && ssh-add ~/.ssh/id_rsa
          # 信任域名
          ssh-keyscan -H jihulab.com >> ~/.ssh/known_hosts
          # 查看当前分支
          echo 当前分支：$GITHUB_REF_NAME
          # 查看远端 极狐GitLab
          echo git@jihulab.com:$GITHUB_REPOSITORY.git
          # 添加远端 极狐GitLab
          git remote add jihulab git@jihulab.com:$GITHUB_REPOSITORY.git
          # 拉取
          git pull --progress -v --no-rebase jihulab $GITHUB_REF_NAME
          # 推送当前分支
          git push --progress jihulab $GITHUB_REF_NAME:$GITHUB_REF_NAME
          # 推送所有标签
          git push --tags --progress jihulab
          echo "GITHUB_REPOSITORY:$GITHUB_REPOSITORY"
          jihulab_project_id=$(printf "%s" "$GITHUB_REPOSITORY" | jq -s -R -r @uri)
          echo "jihulab_project_id:$jihulab_project_id"
          # 发布 极狐GitLab
          curl --header 'Content-Type: application/json' \
              --header "PRIVATE-TOKEN: ${{ secrets.JIHULAB_PRIVATE_TOKEN }}" \
              --data '{ "name": "v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}", "tag_name": "v0.0.0-${{ env.YEAR_MONTH_DAY_HOUR_MINUTE }}", "description": "" }' \
              --request POST "https://jihulab.com/api/v4/projects/$jihulab_project_id/releases"

      # 将代码同步到 码云Gitee
      - name: Sync Gitee
        run: |
          git config --global user.email "xuxiaowei@xuxiaowei.com.cn"
          git config --global user.name "徐晓伟"
          git remote add gitee https://xuxiaowei-com-cn:${{ secrets.GITEE_PRIVATE_TOKEN }}@gitee.com/$GITHUB_REPOSITORY.git
          # 推送当前分支
          git push --progress gitee $GITHUB_REF_NAME:$GITHUB_REF_NAME
          # 推送所有标签
          git push --tags --progress gitee
